name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: pnpm/action-setup@v4
      with:
        version: 12.5.1
        run_install: false
    - uses: actions/setup-node@v7
      with:
        node-version: 22.22.2
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
    - run: pnpm --dir ./packages/backend lint

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: pnpm/action-setup@v4
      with:
        version: 12.5.1
        run_install: false
    - uses: actions/setup-node@v7
      with:
        node-version: 22.22.2
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
    - run: pnpm --dir ./packages/client lint
